version: '3.7'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - "5672:5672"
      - "15672:15672"

  TweetService:
    image: tweetservice
    build:
      context: .
      dockerfile: ./TweetService/Dockerfile
    ports:
      - "9090:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
        
  CommentService:
    image: commentservice
    build:
      context: .
      dockerfile: ./CommentService/Dockerfile
    ports:
      - "9092:80"      