version: '3.7'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  APIGateway:
    image: apigateway
    build:
      context: .
      dockerfile: ./APIGateway/Dockerfile
    ports:
      - "5206:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  AuthorisationService:
    image: authorisationservice
    build:
      context: .
      dockerfile: ./AuthorisationService/Dockerfile
    depends_on:
      - APIGateway
    ports:
      - "9094:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  UserService:
    image: userservice
    build:
      context: .
      dockerfile: ./UserService/Dockerfile
    depends_on:
      - AuthorisationService
    ports:
      - "9093:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  TweetService:
    image: tweetservice
    build:
      context: .
      dockerfile: ./TweetService/Dockerfile
    ports:
      - "9090:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      
  FollowedTweetsService:
    image: followedtweetsservice
    build:
      context: .
      dockerfile: ./FollowedTweetsService/Dockerfile
    depends_on:
      - AuthorisationService
    ports:
      - "9091:80"    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
        
  CommentService:
    image: commentservice
    build:
      context: .
      dockerfile: ./CommentService/Dockerfile
    ports:
      - "9092:80"      
    environment:
      - ASPNETCORE_ENVIRONMENT=Development